#!/bin/sh
# open the app code
tmux new-window 
tmux send-keys 'surfnative' 'C-m'
tmux send-keys 'vim' 'C-m'
tmux rename-window "app"
# open bash window
tmux new-window -n yarn
# start emulator
tmux send-keys 'emulator_fast' 'C-m'
# start yarn server
tmux send-keys 'surfnative' 'C-m'
tmux send-keys 'yin' 'C-m'
tmux send-keys 'yst' 'C-m'
# run demo application
tmux split-window
tmux send-keys 'surfnative' 'C-m'
tmux send-keys 'rnand' 'C-m'
