#!/bin/sh
cp /home/fabrizio/.dotfiles/scripts/utilities/home /usr/bin/home
cp /home/fabrizio/.dotfiles/scripts/utilities/profile /usr/bin/profile
cp /home/fabrizio/.dotfiles/scripts/utilities/remap_control /usr/bin/remap_control
cp /home/fabrizio/.dotfiles/scripts/utilities/remap_right_click /usr/bin/remap_right_click
cp /home/fabrizio/.dotfiles/scripts/utilities/set_laptop_keyboard /usr/bin/set_laptop_keyboard
cp /home/fabrizio/.dotfiles/scripts/utilities/susb /usr/bin/susb
cp /home/fabrizio/.dotfiles/scripts/utilities/buildAndNotify /usr/bin/buildAndNotify
cp /home/fabrizio/.dotfiles/scripts/utilities/buildAndNotifyExpo /usr/bin/buildAndNotifyExpo
chown fabrizio:fabrizio /usr/bin/profile
chown fabrizio:fabrizio /usr/bin/remap_control
chown fabrizio:fabrizio /usr/bin/remap_right_click
chown fabrizio:fabrizio /usr/bin/set_laptop_keyboard
chown fabrizio:fabrizio /usr/bin/susb
chown fabrizio:fabrizio /usr/bin/buildAndNotify
chown fabrizio:fabrizio /usr/bin/buildAndNotifyExpo
chmod +x /usr/bin/profile
chmod +x /usr/bin/remap_control
chmod +x /usr/bin/remap_right_click
chmod +x /usr/bin/set_laptop_keyboard
chmod +x /usr/bin/susb
chmod +x /usr/bin/susb
chmod +x /usr/bin/buildAndNotify
chmod +x /usr/bin/buildAndNotifyExpo
