#!/bin/sh

# create new window
tmux new-window
# use the alias to find path
tmux send-keys "$1" 'C-m'

# rename the window
tmux rename-window "$1"
# open vim
tmux send-keys 'vim' 'C-m'

# open a split
tmux split-window -l 4
tmux send-keys "$1" 'C-m'
