#!/bin/bash
source ~/.dotfiles/env/android
source ~/.dotfiles/env/gradle
source ~/.dotfiles/env/folders
source ~/.dotfiles/env/utilities
source ~/.dotfiles/vimrc
source ~/.dotfiles/environment
source ~/.dotfiles/history
source ~/.zshrc
