#!/bin/sh

# rename session
tmux rename-session "$1 - $2"

# create new window
tmux new-window
# use the alias to find path
tmux send-keys "$2" 'C-m'

# rename the window
tmux rename-window "$2"
# open vim
tmux send-keys 'vim' 'C-m'

# open a split
tmux split-window -l 4
tmux send-keys "$2" 'C-m'
