#!/bin/sh
# environment variables
# export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_251
# export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
# export JAVA_HOME=/usr/lib/jvm/jdk-15.0.2
# export JAVA_HOME=/usr/lib/jvm/jdk-14.0.2
# export JAVA_HOME=/usr/lib/jvm/jdk-14.0.2
# export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:/opt/android-studio/bin
# export PATH=$PATH:/opt/buck/bin
export PATH=$PATH:$HOME/Documents/sourcecode/opensource/buck/bin
export ANDROID_SDK=$HOME/Android/Sdk
# export ANDROID_NDK=$ANDROID_SDK/ndk/17.2.4988734
# export ANDROID_NDK=$ANDROID_SDK/ndk/21.4.7075529
# export ANDROID_NDK=/home/fabrizio/Downloads/android-ndk-r20b-linux-x86_64/android-ndk-r20b
# export ANDROID_NDK=/home/fabrizio/Downloads/android-ndk-r21e-linux-x86_64/android-ndk-r21e
export REACT_EDITOR="/usr/bin/nvim"
# alias
alias emulator_api='emulator -avd Pixel_2_API_28_Google_Api'
alias emulator_fast='emulator -avd Pixel_3a_API_28 &'
alias haxm_stop='sudo kextunload –b com.intel.kext.intelhaxm'
alias haxm_start='sudo kextload –b com.intel.kext.intelhaxm'
alias check_haxm='kextstat | grep intel'
alias rnand='yarn react-native run-android'
alias adbm="adb shell input keyevent 82"
alias systeminfo="inxi -Fxz"
alias jshell="/opt/java-se-9-ri/jdk-9/bin/jshell"
alias avds="emulator -list-avds"
alias npmglobal="npm list -g --depth=0"
alias gradle_run='./gradlew :app:assembleDebug --daemon'
alias rnlog="yarn react-native log-android"
alias packager="./scripts/packager.sh"
alias gt='ctags -R --excmd=number'
alias change_java="sudo update-alternatives --config java"
alias show_touches="adb shell settings put system show_touches 1"
alias al="adb logcat"

# os
alias rntester="./gradlew :RNTester:android:app:installJscDebug"

# functions
function adg() {
  adb logcat G "$1"
}

function clg() {
  ~/.dotfiles/scripts/android/coloredlogcat.py | grep $1
}
