#!/bin/sh
alias server="DEBUG_COLORS=true DEBUG=express:* yarn dev"
export PATH=$PATH:~/Applications/arcanist/bin
alias dsql="docker exec -it my-mysql mysql -p"
alias sqlstart="docker start fa11609c5c4504f0c7eca682926b47cc1bd65b79b332eb11474ebba8adde8ef6"
alias adbreverse="adb reverse tcp:9090 tcp:9090"
