#!/bin/sh
# Environment
export DOCS=$HOME/Documents
export CODE=$DOCS/sourcecode
export OS=$CODE/opensource
export scripts=~/.scripts/bin
export RAILSPATH="$CODE/opensource/rails/"
export GITHUB_TOKEN="78a72af35445ca3f8180b1a98e0bbd56ff1ccba1"
export GITHUB_PR_NUMBER="28617"

# Settings
alias desktop_entries="cd /home/fabrizio/.local/share/applications"

# Open Source folders
alias code="cd $DOCS/sourcecode"
alias os="cd $CODE/opensource"

# Projects Aliases
alias surfnative="cd $CODE/reactnative/surfnative" 
alias surfnotes="vim ~/Documents/Notes/Surfcheck"
alias railspath="cd $CODE/rails"
alias association="cd $RAILSPATH/activerecord/lib/active_record/associations"
alias relation="cd $RAILSPATH/activerecord/lib/active_record/relation"
alias rncamera="cd $CODE/opensource/react-native-camera"
alias rnlibs="cd $CODE/reactnative/libraries"
alias portfolio="cd $CODE/rails/portfolio"
alias social="cd $CODE/rails/SocialNetwork"
alias sprachspiel="cd $CODE/rails/SpracheSpiel"
alias surf="cd $CODE/rails/surfcheck"
alias myapp="cd $CODE/android/MyApplication"
alias snippets="os && vim-snippets"

# React Native OpenSource
alias reactnative="cd $CODE/opensource/react-native-fork"
alias aosp="cd $CODE/opensource/platform_frameworks_base/core/java/android"
alias androidx="cd $CODE/opensource/androidx"
alias slider="cd $CODE/opensource/react-native-slider"
alias progressbar="cd $CODE/opensource/progress-bar-android"
