#!/bin/sh

## delete all branches except master
# alias gbr="git branch | grep -v "master" | xargs git branch -D"

# https://www.makeuseof.com/inspect-project-history-git-log/
# git log --since="2021-01-01" --until="2021-05-01"

alias gs="gst"

# filter commits that are not mine
# https://stackoverflow.com/a/4262780/7295772
alias glnotme="glo --author='^(?!fabriziobertoglio1987).*$' --perl-regexp"
alias glme="glg --author=fabriziobertoglio1987"
alias glm="glco 10"
alias gitclean="git clean -fdx"

function glco() {
  glme $2 --max-count=$1
}

function gours() {
  git checkout --ours $1
}

function gtheirs() {
  git checkout --theirs $1
}
