#!/bin/sh
alias ysr="./scripts/packager.sh"
alias bta="./scripts/run-android-local-unit-tests.sh"
alias btf="buck test ReactAndroid/src/test/java/com/facebook/react/views:views --test-selectors 'com.facebook.react.views.image.ReactImagePropertyTest#testRoundedCorners'"
alias adbg="adbgrep 'TESTING::'"
# alias ybr="./gradlew :packages:rn-tester:android:app:installJscDebug"
alias ybr="./gradlew :packages:rn-tester:android:app:installJscDebug -PreactNativeArchitectures=x86_64"
alias ysa="adb shell am start -n 'com.facebook.react.uiapp/com.facebook.react.uiapp.RNTesterActivity' -a android.intent.action.MAIN -c android.intent.category.LAUNCHER"
# alias ybr="ybuildrn && ysa"
alias rnand='yarn react-native run-android'
alias aoff="adb shell settings put secure enabled_accessibility_services com.android.talkback/com.google.android.marvin.talkback.TalkBackService"
alias aon="adb shell settings put secure enabled_accessibility_services com.google.android.marvin.talkback/com.google.android.marvin.talkback.TalkBackService"
alias cocrn="echo 'y' | cp ~/.dotfiles/files/config_js.json ~/.config/nvim/coc-settings.json"
alias aw="cd /home/fabrizio/Documents/sourcecode/reactnative/AwesomeProject"

# https://github.com/CommE2E/comm/blob/master/docs/dev_environment.md#nvm
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
