#!/bin/sh
# rename session
tmux rename-session "algo"
# open js library
tmux new-window
tmux rename-window "vim"

# open react native
tmux send-keys 'code && cd algo' 'C-m'
tmux send-keys 'vim' 'C-m'

# open a split
tmux split-window -h -l 40
tmux send-keys "code && cd algo" 'C-m'
