#!/bin/sh
# open vim library
tmux rename-session "a - rncamera"
tmux new-window -n lib
tmux send-keys 'rncamera' 'C-m'
# tmux send-keys 'cd android' 'C-m'
tmux send-keys 'vim' 'C-m'
# open bash window
tmux new-window -n zsh
tmux send-keys 'rncamera' 'C-m'
# # open vim library
# tmux new-window -n example
# tmux send-keys 'rncamera' 'C-m'
# tmux send-keys 'cd examples/basic' 'C-m'
# tmux send-keys 'vim' 'C-m'
# # open bash window
# tmux new-window -n zsh
# tmux send-keys 'rncamera' 'C-m'
# tmux send-keys 'cd examples/basic' 'C-m'
