#!/bin/sh
# rename session
tmux rename-session "e - expo"
# open js library
tmux new-window

tmux rename-window "expo"

# copy js settings
# tmux send keys "echo 'y' | cp ~/.dotfiles/files/config_ts.json ~/.config/nvim/coc-settings.json" 'C-m'

tmux send-keys 'os' 'C-m'
tmux send-keys 'cd expo' 'C-m'
tmux send-keys 'adbm &&' 'C-m'
tmux send-keys 'vim' 'C-m'

# open bash window
tmux split-window -l 4
tmux send-keys 'os' 'C-m'
tmux send-keys 'cd expo/apps/bare-expo' 'C-m'
tmux send-keys 'yarn android' 'C-m'
tmux send-keys './scripts/start.command' 'C-m'

# open packages folder in new window
# tmux new-window
# tmux rename-window "packages"
# tmux send-keys 'os' 'C-m'
# tmux send-keys 'cd expo/packages' 'C-m'
# tmux send-keys 'vim' 'C-m'

# open bash window
tmux new-window
tmux rename-window "bash"
tmux send-keys 'os' 'C-m'
tmux send-keys 'cd expo' 'C-m'
# tmux send-keys './scripts/start.command' 'C-m'
