#!/bin/sh
# open vim 
tmux rename-session "b - portfolio"
tmux new-window -n vim
tmux send-keys 'portfolio' 'C-m'
tmux send-keys 'vim' 'C-m'

# open bash window
tmux new-window -n bash
tmux send-keys 'portfolio' 'C-m'
